packages:
  - playgrounds/*
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@antfu/ni': ^24.3.0
  '@antfu/utils': ^9.1.0
  '@eslint-react/eslint-plugin': ^1.40.1
  '@shikijs/core': ^3.0.0
  '@shikijs/engine-javascript': ^3.2.1
  '@shikijs/langs': ^3.2.1
  '@shikijs/themes': ^3.2.1
  '@types/node': ^22.13.17
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  '@unocss/reset': ^66.0.0
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-react-swc': ^3.8.1
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.0.0
  bumpp: ^10.1.0
  eslint: ^9.23.0
  lint-staged: ^15.5.0
  pnpm: ^10.7.1
  react: ^19.1.0
  react-dom: ^19.1.0
  shiki: ^3.2.1
  simple-git-hooks: ^2.12.1
  tsx: ^4.19.3
  typescript: ~5.8.2
  unbuild: ^3.5.0
  unocss: ^66.0.0
  vite: ^6.2.4
  vite-plugin-solid: ^2.11.6
  vitest: ^3.1.1
  vue: ^3.5.13
  vue-tsc: ^2.2.8
